# Judge0 Configuration

# Database
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0_db_password

# Redis
REDIS_PASSWORD=judge0_redis_password

# Server Config
ENABLE_WAIT_FOR_RETURN=true
ENABLE_COMPILER_OPTIONS=true
ENABLE_COMMAND_LINE_ARGUMENTS=true
ALLOW_ENABLE_NETWORK=true
